import { defineNuxtModule, addComponent, createResolver } from '@nuxt/kit';

export interface ModuleOptions {
  prefix: string;
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@rivo-icons/nuxt',
    configKey: 'rivoIcons',
    compatibility: { nuxt: '>=3.0.0' },
  },
  defaults: {
    prefix: 'Icon',
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);

    // Icons are auto-registered after icons:generate runs
    // Each generated icon from @rivo-icons/vue is added as a global component
    // Example registration (generated by scripts/generate.ts):
    //
    // await addComponent({
    //   name: `${options.prefix}Home`,
    //   export: 'Home',
    //   filePath: '@rivo-icons/vue',
    // });
  },
});
