export type { IconMeta, IconData, IconVariant } from '@rivo-icons/shared';

// Generated by scripts/generate.ts — do not edit manually
export const RIVO_ICONS_VERSION = '0.0.1';

// icon data exports will be appended here after running icons:generate
